### ISSUE TITLE
TypeError: Cannot find function debounce in object [object Object]. at 620274c551b2481a8a097f18.js:3:0

### ISSUE THREAD

**Issue by kimljx** [hamibot/hamibot#102]
**错误描述**
今早突然出现的，平时运行的好好的，我脚本没有debounce这个fuction，以下是完整错误日志。
08:39:55.641/E: TypeError: Cannot findfunction debounce in object [object Object]61a490a116133dca0e947eaf.is#3)TypeError: Cannot find function debounce in objectlobject Object].
at 61a490a116133dca0e947eaf.js:3:0

**错误复现**
每次运行脚本都会出现

**Comment by kimljx** [comment]
![20231122085852](https://github.com/hamibot/hamibot/assets/19872214/c7227199-61bc-41ee-9692-fd4a635f2807)

**Comment by Syntax-J** [comment]
@kimljx 是不是用了postMessage这个方法 好像用了这个就会报错
