### ISSUE TITLE
captureScreen()截取横屏失效问题

### ISSUE THREAD

**Issue by eschh19** [hamibot/hamibot#73]
现象：已申请和赋予截取横屏的权限，使用captureScreen()截取后，再使用images.findMultiColors()指定区域的时候，提示超出了范围，实际是在屏幕范围中的。
相关代码：
requestScreenCapture(true);
setScreenMetrics(1080, 2520);
images.findMultiColors(captureScreen(), '#f32d05', [[-74, 69, '#0159ce']], {
        region: [2270, 50, 120, 150],
        threshold: 30
    });

**Comment by batu1579** [comment]
可以看看报错信息嘛？

我目前没看出什么问题，但是也许可能是因为获取权限后需要一段时间（几百ms）才会获取到截取的图片。当然这只是我的猜测QAQ

**Comment by eschh19** [comment]
> 可以看看报错信息嘛？
> 
> 我目前没看出什么问题，但是也许可能是因为获取权限后需要一段时间（几百ms）才会获取到截取的图片。当然这只是我的猜测QAQ

报错信息是：
14:58:57.698/E: Error: out of region: region = [2270,50,120,150], image.size = [1080,2520] (file:///android_asset/modules/__images__.js#523)
Error: out of region: region = [2270,50,120,150], image.size = [1080,2520]
    at buildRegion (file:///android_asset/modules/__images__.js:523:0)
    at file:///android_asset/modules/__images__.js:395:0

**Comment by eschh19** [comment]
> 可以看看报错信息嘛？
> 
> 我目前没看出什么问题，但是也许可能是因为获取权限后需要一段时间（几百ms）才会获取到截取的图片。当然这只是我的猜测QAQ

如果是这个原因的话，是需要每次截屏后，手动等待一段时间，再往下操作吗？

**Comment by batu1579** [comment]
哦哦我找到出错的地方了，这里是因为你设置了屏幕缩放时用的是竖屏的尺寸。

报错信息的所在位置在这里：

https://github.com/hamibot/hamibot/blob/15d7d7b8c8ef118169da8d04896f4b288df5341b/autojs/src/main/assets/modules/__images__.js#L522-L524

其中你的 x（2270） + width（120） > img.width（1080） 所以才导致抛出异常。

如果你把屏幕缩放的参数调换位置，应该就能解决了：

```javascript
requestScreenCapture(true);

setScreenMetrics(2520, 1080);  // 这里使用横屏的宽高

images.findMultiColors(
    captureScreen(),
    '#f32d05',
    [
        [-74, 69, '#0159ce']
    ],
    {
        region: [2270, 50, 120, 150],
        threshold: 30
    }
);
```

**Comment by eschh19** [comment]
> ```js
> setScreenMetrics(2520, 1080);
> ```

好的， 我试试###

**Comment by batu1579** [comment]
> > ```js
> > setScreenMetrics(2520, 1080);
> > ```
> 
> 好的， 我试试###

如何辣？解决了嘛？

**Comment by MannixGu** [comment]
realme上面截图，下来发现没有图像，15kb只有黑色的，截图权限已经获取了
captureScreen("/sdcard/Download/hhh.jpg")

**Comment by 1049731887** [comment]
@hamibot 此issue可以关闭

**Comment by lvq410** [comment]
setScreenMetrics(2520, 1080);  // 这里使用横屏的宽高

这个函数是做什么用的，在文档里好像没有看到

**Comment by tiaotiaolove** [comment]
### 在1.6.5版本中，我也遇到相同的问题：

- 脚本启动的时候，在主线程中获取截图权限，构建悬浮窗按钮，然后由悬浮窗按钮触发事件，启动1个新线程threads.start(function() {})，在线程中执行的截图找点。

- 我在升级1.6.5之前（1.6.2版本）是好好的，代码没有任何变动的情况下，截图的尺寸突然变成了1080 * 2400了，之前都是2400 * 1080；即使设置setScreenMetrics(2400, 1080);也没用...

重启手机后，然后在横屏模式下，通过电脑远程启动脚本才解决，感觉有缓存。而且重启后，不能设置setScreenMetrics(2400, 1080)，设置的话，x、y坐标就颠倒了。只能设置setScreenMetrics(1080, 2400)。
